// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Delay: typeof import('./src/components/AsyncComponents/Delay.vue')['default']
    LargeImg: typeof import('./src/components/AsyncComponents/LargeImg.vue')['default']
    'Provide & Inject': typeof import('./src/components/CrossComponents/Provide & Inject.vue')['default']
    UseReactive: typeof import('./src/components/CrossComponents/UseReactive.vue')['default']
    UseVuex: typeof import('./src/components/CrossComponents/UseVuex.vue')['default']
    Base: typeof import('./src/components/CssVar/base.vue')['default']
    UseCssModule: typeof import('./src/components/CssVar/useCssModule.vue')['default']
    UseCssVars: typeof import('./src/components/CssVar/useCssVars.vue')['default']
    UseAttrs: typeof import('./src/components/Fragments/UseAttrs.vue')['default']
    UseContext: typeof import('./src/components/ScriptSetup/useContext.vue')['default']
    VarDescriptions: typeof import('./src/components/VarDescriptions/index.vue')['default']
    Deep: typeof import('./src/components/Watch/Deep.vue')['default']
    Flush: typeof import('./src/components/Watch/Flush.vue')['default']
    Immediate: typeof import('./src/components/Watch/Immediate.vue')['default']
    MultipleSource: typeof import('./src/components/Watch/MultipleSource.vue')['default']
    SingleSourceWithGetter: typeof import('./src/components/Watch/SingleSourceWithGetter.vue')['default']
    SingleSourceWithRef: typeof import('./src/components/Watch/SingleSourceWithRef.vue')['default']
    WatchArray: typeof import('./src/components/Watch/WatchArray.vue')['default']
    WatchObject: typeof import('./src/components/Watch/WatchObject.vue')['default']
    FetchDemo: typeof import('./src/components/WatchEffect/FetchDemo.vue')['default']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NButton: typeof import('naive-ui')['NButton']
    NSpace: typeof import('naive-ui')['NSpace']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayout: typeof import('naive-ui')['NLayout']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NH2: typeof import('naive-ui')['NH2']
    NH4: typeof import('naive-ui')['NH4']
    NH3: typeof import('naive-ui')['NH3']
    NSlider: typeof import('naive-ui')['NSlider']
  }
}

export { }
