// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DesTable: typeof import('./../src/components/DesTable/index.vue')['default']
    GridLayout: typeof import('./../src/layout/GridLayout.vue')['default']
    MainLayout: typeof import('./../src/layout/MainLayout.vue')['default']
  }
}

export { }
